### ISSUE TITLE
Customer ID is invalid

### ISSUE THREAD

**Issue by digason** [KuriousAgency/commerce-braintree#24]
Attempting to create a new subscription and am receiving the following error:

craft\commerce\errors\PaymentSourceException: Customer ID is invalid. in /Users/Shared/Sites/abcdefg.com/vendor/kuriousagency/commerce-braintree/src/gateways/Gateway.php:257
Stack trace:
#0 /Users/Shared/Sites/abcdefg.com/vendor/craftcms/commerce/src/services/PaymentSources.php(185): kuriousagency\commerce\braintree\gateways\Gateway->createPaymentSource(Object(kuriousagency\commerce\braintree\models\Payment), 16823)
#1 /Users/Shared/Sites/abcdefg.com/vendor/craftcms/commerce/src/controllers/SubscriptionsController.php(217): craft\commerce\services\PaymentSources->createPaymentSource(16823, Object(kuriousagency\commerce\braintree\gateways\Gateway), Object(kuriousagency\commerce\braintree\models\Payment))
#2 [internal function]: craft\commerce\controllers\SubscriptionsController->actionSubscribe()
#3 /Users/Shared/Sites/abcdefg.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/Shared/Sites/abcdefg.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /Users/Shared/Sites/abcdefg.com/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('subscribe', Array)
#6 /Users/Shared/Sites/abcdefg.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('subscribe', Array)
#7 /Users/Shared/Sites/abcdefg.com/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('commerce/subscr...', Array)
#8 /Users/Shared/Sites/abcdefg.com/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('commerce/subscr...', Array)
#9 /Users/Shared/Sites/abcdefg.com/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /Users/Shared/Sites/abcdefg.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /Users/Shared/Sites/abcdefg.com/web/index.php(21): yii\base\Application->run()
#12 {main}

This results in a message of "Unable to start the subscription. Please check your payment details." on the front end.

After contacting Braintree support, this is what they had to say:

> At the moment the issues we're seeing on our server logs are that your customer ids are invalid. One such example of this invalid customer id is xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx​. The reason this ID in invalid is because it doesn't exist in your vault. 

>You've mentioned that you're using a plugin, there may be some configuration issue with it, however as Braintree don't develop plugins for any platform I don't have any insight as to what is causing the issue. Your best course of action would be to contact the developer of your plugin and mention the information I have provided you with.

**Comment by digason** [comment]
It looks like I needed to pass {vault:true} to getPaymentFormHtml()
