### ISSUE TITLE
Fatal error: Uncaught Braintree\Exception\Authorization

### ISSUE THREAD

**Issue by mrmoni** [KuriousAgency/commerce-braintree#43]
Fatal error: Uncaught Braintree\Exception\Authorization in C:\xampp\htdocs\pmteacher\vendor\braintree\braintree_php\lib\Braintree\Util.php:66 Stack trace: #0 C:\xampp\htdocs\pmteacher\vendor\braintree\braintree_php\lib\Braintree\Http.php(76): Braintree\Util::throwStatusCodeException(403) #1 C:\xampp\htdocs\pmteacher\vendor\braintree\braintree_php\lib\Braintree\TransactionGateway.php(705): Braintree\Http->post('/merchants/3gv8...', Array) #2 C:\xampp\htdocs\pmteacher\vendor\braintree\braintree_php\lib\Braintree\TransactionGateway.php(53): Braintree\TransactionGateway->_doCreate('/transactions', Array) #3 C:\xampp\htdocs\pmteacher\vendor\braintree\braintree_php\lib\Braintree\TransactionGateway.php(429): Braintree\TransactionGateway->create(Array) #4 C:\xampp\htdocs\pmteacher\payment_checkout.php(31): Braintree\TransactionGateway->sale(Array) #5 {main} thrown in C:\xampp\htdocs\pmteacher\vendor\braintree\braintree_php\lib\Braintree\Util.php on line 66

**Comment by daniellelecomte** [comment]
@mrmoni - Do you have Test Mode turned on?
